### PR TITLE
Update app.php

### PR DESCRIPTION
**Pull request by DomenicoParisiWeb**
Added some env variables + Added Italian language support.

### CODE REVIEW

**Comment by DomenicoParisiWeb** [comment]
IT lang folder: https://easyupload.io/sqpdb7

**Comment by eusonlito** [comment]
Ok, why you don't add the `it` lang folder to this PR?

**Comment by DomenicoParisiWeb** [comment]
How do you create a folder?  I only see "add file"...

**Comment by eusonlito** [comment]
Adding folder from your fork with a commit.

**Comment by DomenicoParisiWeb** [comment]
https://github.com/eusonlito/Password-Manager/pull/55

**Pull request closed without merging**
